# These are supported funding model platforms

github: [wolffshots] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: wolffshots # Replace with a single Open Collective username
ko_fi: wolffshots # Replace with a single Ko-fi username
custom: ['https://www.buymeacoffee.com/wolffshots'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
