name: phocus

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set Go private repos
      run: go env -w GOPRIVATE="github.com/wolffshots/*"
      
    - name: Checkout default messages
      uses: actions/checkout@v3
      with: 
        repository: wolffshots/phocus_messages
        path: messages
  
    - name: Go mod tidy
      run: go mod tidy

    - name: Build
      run: go build -o ./phocus -v main.go
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set Go private repos
      run: go env -w GOPRIVATE="github.com/wolffshots/*"

    - name: Checkout default messages
      uses: actions/checkout@v3
      with: 
        repository: wolffshots/phocus_messages
        path: messages

    - name: Go mod tidy
      run: go mod tidy

    - name: Install socat
      run: sudo apt-get install -y socat

    - name: Test with coverage profile
      run: go test -v ./... -coverprofile=coverage.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

    - name: Upload coverage reports to Codacy
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test, build]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set Go private repos
      run: go env -w GOPRIVATE="github.com/wolffshots/*"

    - name: Checkout default messages
      uses: actions/checkout@v3
      with: 
        repository: wolffshots/phocus_messages
        path: messages

    - name: Go mod tidy
      run: go mod tidy

    - name: Build
      run: go build -o ./phocus -v main.go
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      if: github.ref == 'refs/heads/main'
      with:
        name: phocus
        path: phocus*
