name: phocus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set Go private repos
      run: go env -w GOPRIVATE="github.com/wolffshots/*"

    - name: Build
      run: go build -o ./phocus -v main.go
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: phocus
        path: phocus*
        
    - name: Test
      run: go test -v ./...
      

