name: svelte

on:
  workflow_dispatch:
  push:
    paths-ignore:
        - '**/*.go'
        - '**/go.mod'
        - '**/go.sum'
        - '**/*.md'
        - 'LICENSE'
        - '**/*.sh'
        - '**/*.service'
        - '**/*.json*'
        - '.github/*.yml'

defaults:
    run:
        working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print event JSON
        run: cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
            node-version: 21.6.2

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
            path: |
                ./node_modules
                ./web/node_modules
                ./.svelte-kit
                ./web/.svelte-kit
            key: npm-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
            node-version: 21.6.2

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
            path: |
                ./node_modules
                ./web/node_modules
                ./.svelte-kit
                ./web/.svelte-kit
            key: npm-${{ hashFiles('**/package-lock.json') }}

      - run: npx playwright install

      - run: npm run test
